### PR TITLE
First try: add CAP exhibit

### PR DESCRIPTION
**Pull request by rebeccacremona**
See ENG-649.

This is a rough attempt to add exhibits from the Caselaw Access Project.

The associates WARC and WACZ files have already been uploaded to the bucket, but due to CORS restrictions, I could not test this PR locally. So I have no idea if any of the playbacks work, or if this is full of typos 🤣. I suspect it is easiest to merge and let me find errors live... if we can tolerate that.

This PR cherry-picks the [deep link commits](https://github.com/harvard-lil/museum.lil.tools/pull/1) from Matteo's draft PR, but amends them to drop the edits to H2O-related files. Instead, it loads `archive.js` into `chronolawgic.html`, where it attempts to use that mechanism to navigate between timelines. That is, again, untested, for the same reason: no working playback because of CORS.

Reasons to object to this PR:
- it's styling may not be good enough yet (I think it is okay?)
- it may be preferable for me to test locally using some technique I have not thought of

But, I'm hoping it's good enough for jazz. Or at least, a first play-through of some jazz 😉

### CODE REVIEW

**Comment by rebeccacremona** [comment]
image
image
image
image

**Review by matteocargnelutti — APPROVED** [review]
Huge fan

**Comment by rebeccacremona** [comment]
(actual review was out loud in the office 😀. i'll follow up with suggested changes in the AM)

**Comment by rebeccacremona** [comment]
Per feedback, I switched Chronolawgic's featured timelines from a long list to a select.
image
image

**Comment by rebeccacremona** [comment]
IIRC, that was the only note.

I'll post the wicked cool deploy preview link (!!!!!) somewhere others can see it, and will prepare to merge unless anyone objects.

(Whoa Netlify)

**Pull request merged**
